// <auto-generated />
using System;
using ApiWebBasicPlatFrom.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Nguyen_Khanh_Thu_193865.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240516122754_addSoLuong")]
    partial class addSoLuong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nguyen_Khanh_Thu_193865.Entites.Product193865De3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product193865De3", (string)null);
                });

            modelBuilder.Entity("Nguyen_Khanh_Thu_193865.Entites.Shipper193865De3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaShipper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shipper193865De3", (string)null);
                });

            modelBuilder.Entity("Nguyen_Khanh_Thu_193865.Entites.ShipperProduct193865De3", b =>
                {
                    b.Property<int>("ShipperID")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ShipperID", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShipperProduct193865De3", (string)null);
                });

            modelBuilder.Entity("Nguyen_Khanh_Thu_193865.Entites.ShipperProduct193865De3", b =>
                {
                    b.HasOne("Nguyen_Khanh_Thu_193865.Entites.Product193865De3", "product193865")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product193865De3_ShipperProduct193865De3");

                    b.HasOne("Nguyen_Khanh_Thu_193865.Entites.Shipper193865De3", "shipper193865")
                        .WithMany()
                        .HasForeignKey("ShipperID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_shipper193865_ShipperProduct193865De3");

                    b.Navigation("product193865");

                    b.Navigation("shipper193865");
                });
#pragma warning restore 612, 618
        }
    }
}
