// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenDucManh0210668.DbContexts;

#nullable disable

namespace NguyenDucManh0210668.Migrations
{
    [DbContext(typeof(AppDbContext0210668De1))]
    [Migration("20260603030402_InitialCreate0210668De1")]
    partial class InitialCreate0210668De1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NguyenDucManh0210668.Entities.DuAn0210668De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaDuAn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("MaDuAn")
                        .IsUnique();

                    b.HasIndex("TenDuAn")
                        .IsUnique();

                    b.ToTable("DuAns", (string)null);
                });

            modelBuilder.Entity("NguyenDucManh0210668.Entities.NhanVien0210668De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.ToTable("NhanViens", (string)null);
                });

            modelBuilder.Entity("NguyenDucManh0210668.Entities.PhanCong0210668De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuAnId")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("SoGioLamViec")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DuAnId");

                    b.HasIndex("NhanVienId", "DuAnId")
                        .IsUnique();

                    b.ToTable("PhanCongs", (string)null);
                });

            modelBuilder.Entity("NguyenDucManh0210668.Entities.PhanCong0210668De1", b =>
                {
                    b.HasOne("NguyenDucManh0210668.Entities.DuAn0210668De1", "DuAn")
                        .WithMany("PhanCongs")
                        .HasForeignKey("DuAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NguyenDucManh0210668.Entities.NhanVien0210668De1", "NhanVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NguyenDucManh0210668.Entities.DuAn0210668De1", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("NguyenDucManh0210668.Entities.NhanVien0210668De1", b =>
                {
                    b.Navigation("PhanCongs");
                });
#pragma warning restore 612, 618
        }
    }
}
