// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nguyenducmanh0210668.DbContexts;

#nullable disable

namespace nguyenducmanh0210668.Migrations
{
    [DbContext(typeof(AppDbContext0210668De1))]
    partial class AppDbContext0210668De1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("nguyenducmanh0210668.Entities.Enterprise0210668De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.EnterpriseProduct0210668De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("ProductId");

                    b.ToTable("EnterpriseProducts");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.Product0210668De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.EnterpriseProduct0210668De1", b =>
                {
                    b.HasOne("nguyenducmanh0210668.Entities.Enterprise0210668De1", "Enterprise")
                        .WithMany("EnterpriseProducts")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nguyenducmanh0210668.Entities.Product0210668De1", "Product")
                        .WithMany("EnterpriseProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.Enterprise0210668De1", b =>
                {
                    b.Navigation("EnterpriseProducts");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.Product0210668De1", b =>
                {
                    b.Navigation("EnterpriseProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
