@HostAddress = http://localhost:5245

GET {{HostAddress}}/api/enterprises?PageSize=10&PageIndex=1
Accept: application/json

###

GET {{HostAddress}}/api/enterprises?PageSize=10&PageIndex=1&Keyword=ABC
Accept: application/json

###

POST {{HostAddress}}/api/enterprises
Content-Type: application/json

{
  "name": "Cong ty Test",
  "taxCode": "MST999",
  "address": "Can Tho"
}

###

PUT {{HostAddress}}/api/enterprises/1
Content-Type: application/json

{
  "name": "Cong ty ABC Updated",
  "taxCode": "MST001",
  "address": "Ha Noi Updated"
}

###

DELETE {{HostAddress}}/api/enterprises/3
Accept: application/json

###

GET {{HostAddress}}/api/enterprises/1/top-products
Accept: application/json
