// <auto-generated />
using System;
using DucManhJr1234.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DucManhJr1234.Migrations
{
    [DbContext(typeof(AppDbContext1234De1))]
    [Migration("20260527041057_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DucManhJr1234.Entities.Enterprise1234De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("Enterprises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ha Noi",
                            Name = "Cong ty ABC",
                            TaxCode = "MST001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "TP HCM",
                            Name = "Cong ty XYZ",
                            TaxCode = "MST002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Da Nang",
                            Name = "Cong ty Demo",
                            TaxCode = "MST003"
                        });
                });

            modelBuilder.Entity("DucManhJr1234.Entities.EnterpriseProduct1234De1", b =>
                {
                    b.Property<int>("EnterpriseId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("EnterpriseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("EnterpriseProducts", (string)null);

                    b.HasData(
                        new
                        {
                            EnterpriseId = 1,
                            ProductId = 1,
                            Quantity = 20
                        },
                        new
                        {
                            EnterpriseId = 1,
                            ProductId = 2,
                            Quantity = 50
                        },
                        new
                        {
                            EnterpriseId = 1,
                            ProductId = 3,
                            Quantity = 50
                        },
                        new
                        {
                            EnterpriseId = 2,
                            ProductId = 1,
                            Quantity = 15
                        },
                        new
                        {
                            EnterpriseId = 2,
                            ProductId = 4,
                            Quantity = 70
                        });
                });

            modelBuilder.Entity("DucManhJr1234.Entities.Product1234De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SP001",
                            ImportDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laptop Dell"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SP002",
                            ImportDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ban phim co"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SP003",
                            ImportDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chuot khong day"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SP004",
                            ImportDate = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Man hinh 24 inch"
                        });
                });

            modelBuilder.Entity("DucManhJr1234.Entities.EnterpriseProduct1234De1", b =>
                {
                    b.HasOne("DucManhJr1234.Entities.Enterprise1234De1", "Enterprise")
                        .WithMany("EnterpriseProducts")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DucManhJr1234.Entities.Product1234De1", "Product")
                        .WithMany("EnterpriseProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DucManhJr1234.Entities.Enterprise1234De1", b =>
                {
                    b.Navigation("EnterpriseProducts");
                });

            modelBuilder.Entity("DucManhJr1234.Entities.Product1234De1", b =>
                {
                    b.Navigation("EnterpriseProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
