// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nguyenducmanh0210668.DbContexts;

#nullable disable

namespace nguyenducmanh0210668.Migrations
{
    [DbContext(typeof(AppDbContext0210668De1))]
    partial class AppDbContext0210668De1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("nguyenducmanh0210668.Entities.ChiTietGiaoHang0210668De1", b =>
                {
                    b.Property<int>("ShipperId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShipperId", "SanPhamId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietGiaoHangs");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.SanPham0210668De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaSanPham")
                        .IsUnique();

                    b.HasIndex("TenSanPham")
                        .IsUnique();

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.Shipper0210668De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaShipper")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenShipper")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.HasIndex("MaShipper")
                        .IsUnique();

                    b.HasIndex("TenShipper")
                        .IsUnique();

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.ChiTietGiaoHang0210668De1", b =>
                {
                    b.HasOne("nguyenducmanh0210668.Entities.SanPham0210668De1", "SanPham")
                        .WithMany("ChiTietGiaoHangs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nguyenducmanh0210668.Entities.Shipper0210668De1", "Shipper")
                        .WithMany("ChiTietGiaoHangs")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.SanPham0210668De1", b =>
                {
                    b.Navigation("ChiTietGiaoHangs");
                });

            modelBuilder.Entity("nguyenducmanh0210668.Entities.Shipper0210668De1", b =>
                {
                    b.Navigation("ChiTietGiaoHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
